loadstring(game:HttpGet("https://raw.githubusercontent.com/mainherztbrent/Priv/refs/heads/main/autoclick.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mainherztbrent/Priv/refs/heads/main/atrgl.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mainherztbrent/Priv/refs/heads/main/hitbox.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mainherztbrent/Priv/refs/heads/main/defensa.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/mainherztbrent/Priv/refs/heads/main/teambot.lua"))()
